# Generated by Django 5.0.7 on 2024-11-13 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0048_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FoodHitchApp.customer'),
        ),
        migrations.AddField(
            model_name='message',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FoodHitchApp.rider'),
        ),
    ]
