# Generated by Django 5.0.7 on 2024-11-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0049_message_customer_message_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='PaymentMethod',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('gcash', 'Gcash')], default='cod', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='PaymentStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='ProofOfPayment',
            field=models.ImageField(blank=True, null=True, upload_to='proof_of_payment/'),
        ),
    ]
