# Generated by Django 5.0.7 on 2024-11-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0051_paymentproof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='PaymentStatus',
        ),
    ]
