# Generated by Django 5.0.7 on 2024-11-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0054_order_paymentstatus_delete_paymentproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='DeliveryStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On Transit', 'On Transit'), ('Delivered', 'Delivered'), ('Received', 'Received'), ('Canceled', 'Canceled')], default='Pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='PendingOrder',
        ),
    ]
